[window]
padding = { x = 10, y = 10 }
dynamic_title = true
opacity = 0.8  # Keep at 1.0 to save CPU/GPU resources on HDD

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[colors.primary]
background = '#000000' # Pure Black to match your i3bar
foreground = '#ffffff' # Clean White

[colors.normal]
black =   '#000000'
red =     '#ff5555'
green =   '#50fa7b'
yellow =  '#f1fa8c'
blue =    '#bd93f9'
magenta = '#ff79c6'
cyan =    '#8be9fd'
white =   '#f8f8f2'

[cursor]
style = "Block"
unfocused_hollow = true